trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON_VERSION: '3.12'
  DJANGO_SETTINGS_MODULE: relecloud.settings

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- script: |
    echo "Using Python version:"
    python --version
  displayName: 'Check Python version'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install unittest-xml-reporting
  displayName: 'Install prerequisites'

- script: |
    echo "Running Django tests..."
    python manage.py test --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner
  displayName: 'Run tests (JUnit XML)'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Python $(PYTHON_VERSION)'
  condition: succeededOrFailed()

- script: |
    echo "=== APPLYING DJANGO MIGRATIONS ==="
    python manage.py showmigrations
    python manage.py migrate --noinput
    echo "=== MIGRATIONS FINISHED ==="
  displayName: 'Apply Django migrations'
